package main.java.packages.aircrafts.types.base;

/**
 * Affiliation Enum
 * Contains: Astra Militarum, Sisters of Battle, Space Marine (284) Affiliations
 */
public enum Affiliation {
    ASTRA_MILITARUM("Astra Militarum"),
    SISTERS_OF_BATTLE("Sisters of Battle"),
    ABSOLVERS("Absolvers"),
    ACCIPITERS("Accipiters"),
    ADAMANTINE_LIONS("Adamantine Lions"),
    ADULATORS("Adulators"),
    ALTAR_BRETHREN("Altar Brethren"),
    ANGEL_GUARD("Angel Guard"),
    ANGELS_ENCARMINE("Angels Encarmine"),
    ANGELS_ERADICANT("Angels Eradicant"),
    ANGELS_ERYTHREAN("Angels Erythrean"),
    ANGELS_EXCELSIS("Angels Excelsis"),
    ANGELS_NUMINOUS("Angels Numinous"),
    ANGELS_OF_ABSOLUTION("Angels of Absolution"),
    ANGELS_OF_DAMNATION("Angels of Damnation"),
    ANGELS_OF_DEFIANCE("Angels of Defiance"),
    ANGELS_OF_FIRE("Angels of Fire"),
    ANGELS_OF_FURY("Angels of Fury"),
    ANGELS_OF_IRON("Angels of Iron"),
    ANGELS_OF_LIGHT("Angels of Light"),
    ANGELS_OF_PENANCE("Angels of Penance"),
    ANGELS_OF_PURGATORY("Angels of Purgatory"),
    ANGELS_OF_REDEMPTION("Angels of Redemption"),
    ANGELS_OF_REPENTANCE("Angels of Repentance"),
    ANGELS_OF_RETRIBUTION("Angels of Retribution"),
    ANGELS_OF_THE_GRAIL("Angels of the Grail"),
    ANGELS_OF_VENGEANCE("Angels of Vengeance"),
    ANGELS_OF_VIGILANCE("Angels of Vigilance"),
    ANGELS_OF_WRATH("Angels of Wrath"),
    ANGELS_PENITENT("Angels Penitent"),
    ANGELS_PORPHYR("Angels Porphyr"),
    ANGELS_PUISSANT("Angels Puissant"),
    ANGELS_REDEEMED("Angels Redeemed"),
    ANGELS_REPENTANT("Angels Repentant"),
    ANGELS_RESPLENDENT("Angels Resplendent"),
    ANGELS_REVENANT("Angels Revenant"),
    ANGELS_SANGUINE("Angels Sanguine"),
    ANGELS_VERMILLION("Angels Vermillion"),
    ANGELS_VINDICANT("Angels Vindicant"),
    ARGENT_HAMMERS("Argent Hammers"),
    ASTRAL_BEARS("Astral Bears"),
    ASTRAL_BLADES("Astral Blades"),
    ASTRAL_CLAWS("Astral Claws"),
    ASTRAL_FISTS("Astral Fists"),
    ASTRAL_HAWKS("Astral Hawks"),
    ASTRAL_KNIGHTS("Astral Knights"),
    ASTRAL_SPEARS("Astral Spears"),
    ATLANTIAN_SPEARS("Atlantian Spears"),
    AURIC_PATRICIANS("Auric Patricians"),
    AURORA_CHAPTER("Aurora Chapter"),
    AURORA_TALONS("Aurora Talons"),
    AVENGERS("Avengers"),
    AVENGING_SONS("Avenging Sons"),
    BENEDICTORS("Benedictors"),
    BLACK_CONSULS("Black Consuls"),
    BLACK_CRUSADERS("Black Crusaders"),
    BLACK_DRAGONS("Black Dragons"),
    BLACK_GUARD("Black Guard"),
    BLACK_INCULPATORS("Black Inculpators"),
    BLACK_RAVENS("Black Ravens"),
    BLACK_TALONS("Black Talons"),
    BLACK_TEMPLARS("Black Templars"),
    BLACK_VIPERS("Black Vipers"),
    BLACK_VULTURES("Black Vultures"),
    BLACK_WINGS("Black Wings"),
    BLADES_OF_VENGEANCE("Blades of Vengeance"),
    BLAZONED_LEGION("Blazoned Legion"),
    BLOOD_ANGELS("Blood Angels"),
    BLOOD_DRAGONS("Blood Dragons"),
    BLOOD_DRINKERS("Blood Drinkers"),
    BLOOD_KNIGHTS("Blood Knights"),
    BLOOD_EAGLES("Blood Eagles"),
    BLOOD_LEGION("Blood Legion"),
    BLOOD_RAVENS("Blood Ravens"),
    BLOOD_SCYTHES("Blood Scythes"),
    BLOOD_SWORDS("Blood Swords"),
    BLOOD_TIGERS("Blood Tigers"),
    BONE_KNIVES("Bone Knives"),
    BRAZEN_ANNIHILATORS("Brazen Annihilators"),
    BRAZEN_CONSULS("Brazen Consuls"),
    BRAZEN_CLAWS("Brazen Claws"),
    BRAZEN_FISTS("Brazen Fists"),
    BRAZEN_MINOTAURS("Brazen Minotaurs"),
    BRAZEN_SKULLS("Brazen Skulls"),
    BRINGERS_OF_JUDGEMENT("Bringers of Judgement"),
    BRONZE_GORGONS("Bronze Gorgons"),
    BROTHERS_OF_JARAD("Brothers of Jarad"),
    BROTHERHOOD_OF_A_THOUSAND("Brotherhood of a Thousand"),
    BROTHERS_OF_THE_ANVIL("Brothers of the Anvil"),
    BROTHERS_OF_THE_RED("Brothers of the Red"),
    BROTHERS_PENITENT("Brothers Penitent"),
    BURNING_BLOOD("Burning Blood"),
    CARCHARODONS("Carcharodons"),
    CARMINE_BLADES("Carmine Blades"),
    CASTELLANS_OF_THE_RIFT("Castellans of the Rift"),
    CELEBRANTS("Celebrants"),
    CELESTIAL_GUARD("Celestial Guard"),
    CELESTIAL_LIONS("Celestial Lions"),
    CELESTIAL_SWORDS("Celestial Swords"),
    CELESTIAN_GUARD("Celestian Guard"),
    CERULEAN_GUARD("Cerulean Guard"),
    CHAMPIONS_OF_THANATOS("Champions of Thanatos"),
    CHARNEL_GUARD("Charnel Guard"),
    CHORUS_OF_ELTAIN("Chorus of Eltain"),
    CLERICS_OF_STEEL("Clerics of Steel"),
    CONDEMNORS("Condemnors"),
    CONSECRATORS("Consecrators"),
    CONTENDERS("Contenders"),
    COVENANT_OF_FIRE("Covenant of Fire"),
    COWLED_WARDENS("Cowled Wardens"),
    CRIMSON_CASTELLANS("Crimson Castellans"),
    CRIMSON_CONSULS("Crimson Consuls"),
    CRIMSON_FISTS("Crimson Fists"),
    CRIMSON_GUARD("Crimson Guard"),
    CRIMSON_KNIGHTS("Crimson Knights"),
    CRIMSON_LEGION("Crimson Legion"),
    CRIMSON_PALADINS("Crimson Paladins"),
    CRIMSON_RAPTORS("Crimson Raptors"),
    CRIMSON_SABRES("Crimson Sabres"),
    CRIMSON_SCIONS("Crimson Scions"),
    CRIMSON_SCYTHES("Crimson Scythes"),
    CRIMSON_SHADES("Crimson Shades"),
    CRIMSON_SWORDS("Crimson Swords"),
    CRIMSON_TALONS("Crimson Talons"),
    CRIMSON_TEMPLARS("Crimson Templars"),
    CRUOR_BLADES("Cruor Blades"),
    CRUSADERS("Crusaders"),
    CRUSADERS_OF_DORN("Crusaders of Dorn"),
    DARK_ANGELS("Dark Angels"),
    DARK_BROTHERHOOD("Dark Brotherhood"),
    DARK_CRUSADERS("Dark Crusaders"),
    DARK_EAGLES("Dark Eagles"),
    DARK_HANDS("Dark Hands"),
    DARK_HUNTERS("Dark Hunters"),
    DARK_KRAKENS("Dark Krakens"),
    DARK_PALADINS("Dark Paladins"),
    DARK_SONS("Dark Sons"),
    DARK_SWORDS("Dark Swords"),
    DARK_TEMPLARS("Dark Templars"),
    DEATH_EAGLES("Death Eagles"),
    DEATH_HAWKS("Death Hawks"),
    DEATH_HUNTERS("Death Hunters"),
    DEATH_KNIGHTS("Death Knights"),
    DEATH_SPECTRES("Death Spectres"),
    DEATH_STRIKE("Death Strike"),
    DEATH_WARDENS("Death Wardens"),
    DEATH_WATCH("Deathwatch"),
    DESERT_LIONS("Desert Lions"),
    DESTROYERS("Destroyers"),
    DICTATORS("Dictators"),
    DISCIPLES_OF_BLOOD("Disciples of Blood"),
    DISCIPLES_OF_CALIBAN("Disciples of Caliban"),
    DOOM_EAGLES("Doom Eagles"),
    DOOM_GRIFFONS("Doom Griffons"),
    DOOM_LEGION("Doom Legion"),
    DOOM_WARRIORS("Doom Warriors"),
    DOOMSAYERS("Doomsayers"),
    DRAGONSPEARS("Dragonspears"),
    DRAGON_LORDS("Dragon Lords"),
    EAGLE_WARRIORS("Eagle Warriors"),
    EBON_KNIGHTS("Ebon Knights"),
    EMPERORS_CLAWS("Emperor's Claws"),
    EMPERORS_HANDS("Emperor's Hands"),
    EMPERORS_HAWKS("Emperor's Hawks"),
    EMPERORS_SCYTHES("Emperor's Scythes"),
    EMPERORS_SHADOWS("Emperor's Shadows"),
    EMPERORS_SHIELDS("Emperor's Shields"),
    EMPERORS_SPEARS("Emperor's Spears"),
    EMPERORS_STORM("Emperor's Storm"),
    EMPERORS_SWORDS("Emperor's Swords"),
    EMPERORS_WARBRINGERS("Emperor's Warbringers"),
    EMPERORS_WOLVES("Emperor's Wolves"),
    EMPERORS_WRATH("Emperor's Wrath"),
    ESPANDORS("Espandors"),
    EXCORIATORS("Excoriators"),
    EXCUBANTS("Excubants"),
    EXECRATORS("Execrators"),
    EXECUTIONERS("Executioners"),
    EXEMPLARS("Exemplars"),
    EXORCISTS("Exorcists"),
    EXSANGUINATORS("Exsanguinators"),
    FALLING_STAR("Falling Star"),
    FARSTALKERS("Farstalkers"),
    FIRE_ANGELS("Fire Angels"),
    FIRE_CLAWS("Fire Claws"),
    FIRE_HAWKS("Fire Hawks"),
    FIRE_LORDS("Fire Lords"),
    FIREBREATHERS("Firebreathers"),
    FISTS_EXEMPLAR("Fists Exemplar"),
    FISTS_OF_OLCHIS("Fists of Olchis"),
    FLAME_EAGLES("Flame Eagles"),
    FLAME_FALCONS("Flame Falcons"),
    FLESH_EATERS("Flesh Eaters"),
    FLESH_TEARERS("Flesh Tearers"),
    FULMINATORS("Fulminators"),
    GENESIS_CHAPTER("Genesis Chapter"),
    GOLDEN_BLADES("Golden Blades"),
    GOLDEN_GRYPHONS("Golden Gryphons"),
    GOLDEN_HALOS("Golden Halos"),
    GOLDEN_PALADINS("Golden Paladins"),
    GOLDEN_SONS("Golden Sons"),
    GORGONS("Gorgons"),
    GRAVEN_FISTS("Graven Fists"),
    GRAVEN_SPECTRES("Graven Spectres"),
    GREY_GIANTS("Grey Giants"),
    GREY_KNIGHTS("Grey Knights"),
    GREY_SLAYERS("Grey Slayers"),
    GRIEF_BRINGERS("Grief Bringers"),
    GRIFFON_LORDS("Griffon Lords"),
    GUARDIANS_OF_CELERES("Guardians of Celeres"),
    GUARDIANS_OF_THE_COVENANT("Guardians of the Covenant"),
    HALO_BRETHREN("Halo Brethren"),
    HALO_DRAGONS("Halo Dragons"),
    HAMMERS_OF_DHREX("Hammers of Dhrex"),
    HAMMERS_OF_DORN("Hammers of Dorn"),
    HAMMERS_OF_RETRIBUTION("Hammers of Retribution"),
    HARBINGERS("Harbingers"),
    HAWK_LORDS("Hawk Lords"),
    HELION_LEGION("Helion Legion"),
    HERALDS_OF_ULTRAMAR("Heralds of Ultramar"),
    HERALDS_OF_VENGEANCE("Heralds of Vengeance"),
    HONOURED_SONS("Honoured Sons"),
    HOSPITALLERS("Hospitallers"),
    HOUNDS_OF_DEMOS("Hounds of Demos"),
    HOWLING_GRIFFONS("Howling Griffons"),
    ILLUSTRIANS("Illustrians"),
    IMMORTAL_HEARTS("Immortal Hearts"),
    IMPERIAL_CASTELLANS("Imperial Castellans"),
    IMPERIAL_FISTS("Imperial Fists"),
    IMPERIAL_HARBINGERS("Imperial Harbingers"),
    IMPERIAL_HAWKS("Imperial Hawks"),
    IMPERIAL_PALADINS("Imperial Paladins"),
    IMPERIAL_RAWAGERS("Imperial Ravagers"),
    IMPERIAL_STARS("Imperial Stars"),
    IMPERIAL_TALONS("Imperial Talons"),
    IMPERIUS_REAVERS("Imperius Reavers"),
    INCEPTORS("Inceptors"),
    INCULCATORS("Inculcators"),
    INTERCEPTORS("Interceptors"),
    INVADERS("Invaders"),
    INVICTORS("Invictors"),
    INVIOLATORS("Inviolators"),
    IRON_CHAMPIONS("Iron Champions"),
    IRON_CRUSADERS("Iron Crusaders"),
    IRON_DRAKES("Iron Drakes"),
    IRON_FISTS("Iron Fists"),
    IRON_HANDS("Iron Hands"),
    IRON_HAWKS("Iron Hawks"),
    IRON_HEARTS("Iron Hearts"),
    IRON_HOUNDS("Iron Hounds"),
    IRON_KNIGHTS("Iron Knights"),
    IRON_LORDS("Iron Lords"),
    IRON_RAVENS("Iron Ravens"),
    IRON_SCEPTERS("Iron Scepters"),
    IRON_SHIELD("Iron Shield"),
    IRON_SNAKES("Iron Snakes"),
    IRON_TALONS("Iron Talons"),
    JADE_SCORPIONS("Jade Scorpions"),
    JUSTICARS("Justicars"),
    KNIGHTS_CERULEAN("Knights Cerulean"),
    KNIGHTS_EXCELSIOR("Knights Excelsior"),
    KNIGHTS_OF_ABHORRENCE("Knights of Abhorrence"),
    KNIGHTS_OF_BYZANTIUM("Knights of Byzantium"),
    KNIGHTS_OF_DORN("Knights of Dorn"),
    KNIGHTS_OF_ETERNITY("Knights of Eternity"),
    KNIGHTS_OF_GRYPHONNE("Knights of Gryphonne"),
    KNIGHTS_OF_THE_CHALICE("Knights of the Chalice"),
    KNIGHTS_OF_THE_CRIMSON_ORDER("Knights of the Crimson Order"),
    KNIGHTS_OF_THE_FLAME("Knights of the Flame"),
    KNIGHTS_OF_THE_RAVEN("Knights of the Raven"),
    KNIGHTS_OF_THUNDER("Knights of Thunder"),
    KNIGHTS_SANGUINE("Knights Sanguine"),
    KNIGHTS_UNYIELDING("Knights Unyielding"),
    LAMENTERS("Lamenters"),
    LANCES_OF_PTEROS("Lances of Pteros"),
    LECTORS_OF_IXIS("Lectors of Ixis"),
    LEGION_OF_NIGHT("Legion of Night"),
    LEGION_OF_THE_DAMNED("Legion of the Damned"),
    LIBATORS("Libators"),
    LIBERATORS("Liberators"),
    LION_WARRIORS("Lion Warriors"),
    LIONS_AZURE("Lions Azure"),
    LIONS_DEFIANT("Lions Defiant"),
    LIONS_SABLE("Lions Sable"),
    LIONGUARD("Lionguard"),
    LORDS_OF_WRATH("Lords of Wrath");

    private String name;

    Affiliation(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "Affiliation: '" + name + '\'';
    }
}
